trigger:
  tags:
    include:
    - '*'

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  artifactVersion: $[replace(variables['Build.SourceBranch'], 'refs/tags/', '')]

steps:
  # Based on existing jitpack.yml using java17
  # - task: JavaToolInstaller@0
  #   inputs:
  #     versionSpec: '17'
  #     jdkArchitectureOption: 'x64'
  #     jdkSourceOption:

  - task: AzureKeyVault@2
    displayName: Azure Key Vault
    inputs:
      azureSubscription: 'DTS-CFTPTL-INTSVC'
      KeyVaultName: 'cftptl-intsvc'
      SecretsFilter: 'AZURE-DEVOPS-ARTIFACT-USERNAME, AZURE-DEVOPS-ARTIFACT-TOKEN'

  - script: |
      ./gradlew clean publish
    env:
      AZURE_DEVOPS_ARTIFACT_USERNAME: $(AZURE-DEVOPS-ARTIFACT-USERNAME)
      AZURE_DEVOPS_ARTIFACT_TOKEN: $(AZURE-DEVOPS-ARTIFACT-TOKEN)
      RELEASE_VERSION: $(artifactVersion)
    displayName: 'Publish to Azure DevOps Artifacts'
